name: Fetch accessions
on: [push]
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pysradb
      run: pip install https://github.com/mvdbeek/pysradb/archive/fetch_many_metadata_accessions_at_once.zip
    - name: Fetch accessions
      run: ./fetch_sra_acc.sh
      working-directory: ./genomics/4-Variation/
    - name: Show differences
      run: 'git diff --stat && git diff'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update SARS-CoV-2 accessions"
        title: "Daily update of SARS-CoV-2 accessions"
        labels: Automation
        branch: accession_updates
        base: master
